on: pull_request
name: Node.js CI

jobs:
  test:
    name: Setup and test
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [16.x, 18.x, 20.x]
        # See supported Node.js release schedule at https://nodejs.org/en/about/releases/

    steps:
    - name: Sets env vars (normal)
      run: |
        echo "KEY=${{ vars.KEY }}" >> $GITHUB_ENV
      if: ${{ github.actor != 'dependabot[bot]' }}

    - name: Sets env vars (dependabot)
      run: |
        echo "KEY=${{ secrets.KEY }}" >> $GITHUB_ENV
      if: ${{ github.actor == 'dependabot[bot]' }}

    - uses: actions/checkout@v3
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v3
      with:
        node-version: ${{ matrix.node-version }}

    - name: Install dependencies
      uses: borales/actions-yarn@v4
      with:
        cmd: install

    - name: Test
      uses: borales/actions-yarn@v4
      with:
        cmd: run test
