on: 
  pull_request:
    types:
      - opened
    paths-ignore:
      - 'LICENSE'
      - '.npmignore'
name: Node.js CI

jobs:
  test:
    name: Setup and test
    runs-on: ubuntu-latest
    env:
      KEY: ${{ vars.KEY }}

    strategy:
      matrix:
        node-version: [16.x, 18.x]
        # See supported Node.js release schedule at https://nodejs.org/en/about/releases/

    steps:
    - uses: actions/checkout@v3
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v3
      with:
        node-version: ${{ matrix.node-version }}

    - name: Install dependencies
      uses: borales/actions-yarn@v4
      with:
        cmd: install
    
    - name: Build
      uses: borales/actions-yarn@v4
      with:
        cmd: run build

    - name: Test
      uses: borales/actions-yarn@v4
      with:
        cmd: run test
