name: Publish Package
on:
  release:
    types: [published]

jobs:
  publish-npm:
    name: Publish on NPM
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: '18.x'
          registry-url: 'https://registry.npmjs.org'

      - run: yarn
      - run: yarn publish
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}

  publish-gpr:
    name: Publish on GPR
    runs-on: ubuntu-latest
    # Without it, I'm pretty sure yarn would say it published the package without actually doing it
    # See https://github.com/yarnpkg/yarn/issues/5931
    permissions:
      packages: write

    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: '18.x'
          registry-url: 'https://npm.pkg.github.com/'
          scope: '@tttaevas'

      # See https://github.com/actions/setup-node/issues/156#issuecomment-803057923
      - run: >
          sed -i '/"license"/ i \\  "publishConfig": {\n    "registry": "https://npm.pkg.github.com/"\n \ },' package.json
      - run: yarn
      - run: yarn publish
        env:
          NODE_AUTH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
